/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MazBadge: typeof import('maz-ui/components/MazBadge')['default']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazDataList: typeof import('maz-ui/components/MazDataList')['default']
    MazDataListItem: typeof import('maz-ui/components/MazDataListItem')['default']
    MazIcon: typeof import('maz-ui/components/MazIcon')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    MazPhone: typeof import('maz-ui/components/MazPhone')['default']
    MazPhoneNumberInput: typeof import('maz-ui/components/MazPhoneNumberInput')['default']
    MazSelect: typeof import('maz-ui/components/MazSelect')['default']
    MazSp: typeof import('maz-ui/components/MazSp')['default']
    MazSpinner: typeof import('maz-ui/components/MazSpinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
