/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MazIcon: typeof import('maz-ui/components/MazIcon')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    MazSp: typeof import('maz-ui/components/MazSp')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
