name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t intellisoftdev/lhss_admin_webapp:v1 .

      - name: Log in to Docker registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag the Docker Image
        run: docker tag intellisoftdev/lhss_admin_webapp:v1 intellisoftdev/lhss_admin_webapp:v1-release

      - name: Push Docker image to registry
        run: docker push intellisoftdev/lhss_admin_webapp:v1-release

      - name: SSH into the server and update Docker container
        uses: appleboy/ssh-action@master
        with:
          host: hiedhs.intellisoftkenya.com
          username: pius
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /opt
            docker stop lhss_frontend || true
            docker rm lhss_frontend || true
            docker rmi intellisoftdev/lhss_admin_webapp:v1-release || true
            docker pull intellisoftdev/lhss_admin_webapp:v1-release
            docker run -d --name lhss_frontend -p 5173:5173 intellisoftdev/lhss_admin_webapp:v1-release
